---
title: "checkv_processing"
author: "DLS"
date: "2024-05-27"
output: html_document
---

# Load checkV summary doc
```{r}
# Load output
checkv_out = read.csv("/Users/dinosbardellati/Desktop/PhD_stuff/projects/Bee_phage/5kb/reviewer_comments/checkV_out/quality_summary.tsv", header = T, sep =  "\t")
# take a quick look
head(checkv_out)
# Neat!
```

# Filter to only retain med-high quality seqs (>=50% complete)
```{r}
# First, drop completeness == NA
library(tidyverse)
checkv_out_no_na = checkv_out %>% 
  drop_na(completeness)
# Take a quick look at quality distrobution
ggplot(checkv_out_no_na, aes(completeness)) + 
  geom_density() +
  xlim(-10,110)
# most seqs have a pretty low quality

# Going off of reviewer suggestions, we will subset to completeness >=50%
checkv_out_clean = checkv_out_no_na %>% 
  filter(completeness >= 50)
# Now lets revisualize quality distro
ggplot(checkv_out_clean, aes(completeness)) + 
  geom_density() +
  xlim(-40,110)
# lets also look at length distrobutions
ggplot(checkv_out_clean, aes(contig_length)) + 
  geom_density() 
```

# Export list of med-high quality viral seqs
```{r}
good_seqs = checkv_out_clean$contig_id
write.table(x = good_seqs, 
          file = "/Users/dinosbardellati/Desktop/PhD_stuff/projects/Bee_phage/5kb/reviewer_comments/checkV_out/good_viral_seqs.csv", 
          quote = F, 
          row.names = F, 
          col.names = F,
          sep = ",")
```